samtools sort -n -o ZT0Tx_Rep2.bam ZT0Tx_Rep2.bam          
samtools sort -n -o  ZT0_Tx_rep3_hem.bam ZT0_Tx_rep3_hem.bam      
samtools sort -n -o ZT0V_Rep2.bam ZT0V_Rep2.bam      
samtools sort -n -o ZT0_V_rep3_hem.bam ZT0_V_rep3_hem.bam      
samtools sort -n -o ZT12Tx_Rep2.bam ZT12Tx_Rep2.bam           
samtools sort -n -o ZT12_Tx_rep3_hem.bam ZT12_Tx_rep3_hem.bam      
samtools sort -n -o ZT12V_Rep2.bam ZT12V_Rep2.bam           
samtools sort -n -o ZT12_V_rep3_hem.bam ZT12_V_rep3_hem.bam
samtools sort -n -o ZT0_Tx_rep2_hem.bam ZT0_Tx_rep2_hem.bam      
samtools sort -n -o ZT0Tx_Rep4.bam ZT0Tx_Rep4.bam           
samtools sort -n -o ZT0_V_rep2_hem.bam ZT0_V_rep2_hem.bam      
samtools sort -n -o ZT0V_Rep4.bam ZT0V_Rep4.bam           
samtools sort -n -o ZT12_Tx_rep2_hem.bam ZT12_Tx_rep2_hem.bam      
samtools sort -n -o ZT12Tx_Rep4.bam ZT12Tx_Rep4.bam           
samtools sort -n -o ZT12_V_rep2_hem.bam ZT12_V_rep2_hem.bam      
samtools sort -n -o ZT12V_Rep4.bam ZT12V_Rep4.bam
samtools sort -n -o ZT0Tx_Rep3.bam ZT0Tx_Rep3.bam          
samtools sort -n -o ZT0_Tx_rep4_hem.bam ZT0_Tx_rep4_hem.bam      
samtools sort -n -o ZT0V_Rep3.bam ZT0V_Rep3.bam           
samtools sort -n -o ZT0_V_rep4_hem.bam ZT0_V_rep4_hem.bam      
samtools sort -n -o ZT12Tx_Rep3.bam ZT12Tx_Rep3.bam           
samtools sort -n -o ZT12_Tx_rep4_hem.bam ZT12_Tx_rep4_hem.bam      
samtools sort -n -o ZT12V_Rep3.bam ZT12V_Rep3.bam          
samtools sort -n -o ZT12_V_rep4_hem.bam ZT12_V_rep4_hem.bam
